sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jimmy/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jimmy/docker-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-194829314461"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_key: $AWS_SECRET_ACCESS_KEY

after_success:
  - echo "Test Success"
